### PR TITLE
[ISSUE #2901] EventMeshGrpcConsumerTest repeat subscribe bug

### LINKED ISSUE #2901: [Bug] EventMeshGrpcConsumerTest repeat subscribe bug
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Environment

Mac

### EventMesh version

master

### What happened

expected:<1> but was:<2>
Expected :1
Actual   :2
<Click to see difference>

java.lang.AssertionError: expected:<1> but was:<2>
	at org.junit.Assert.fail(Assert.java:89)

### How to reproduce

add test case

    public void testBuildSubscription() {
        List<SubscriptionItem> subscriptionItems = new ArrayList<>();
        subscriptionItems.add(buildMockSubscriptionItem());
        subscriptionItems.add(buildMockSubscriptionItem());
        Subscription subsription = eventMeshGrpcConsumer.buildSubscription(subscriptionItems, "test_url");
        Assert.assertEquals(1, subsription.getSubscriptionItemsList().size());
    }

### Debug logs

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by jonyangx**
Fixes #2901 .

### Motivation

EventMeshGrpcConsumerTest repeat subscribe bug

### Modifications

replace List with  Set .

### Documentation

- Does this pull request introduce a new feature? (no)
- If yes, how is the feature documented? (not documented)

### CODE REVIEW

File: eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client/grpc/consumer/EventMeshGrpcConsumer.java [hunk 1]
```diff
@@ -130,7 +144,7 @@ public void subscribe(List<SubscriptionItem> subscriptionItems) {
 
     private void addSubscription(List<SubscriptionItem> subscriptionItems, String url) {
         for (SubscriptionItem item : subscriptionItems) {
-            subscriptionMap.put(item.getTopic(), new SubscriptionInfo(item, url));
+            subscriptionMap.putIfAbsent(item.getTopic(), new SubscriptionInfo(item, url));
```
Comment (horoc) [inline eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client/grpc/consumer/EventMeshGrpcConsumer.java:147]: Shall we update the subscription info if the topic exists?

Comment (jonyangx) [reply eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client/grpc/consumer/EventMeshGrpcConsumer.java:147]: ok,I fix it. @horoc

Comment (horoc) [reply eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client/grpc/consumer/EventMeshGrpcConsumer.java:147]: > ok,I fix it. @horoc

@jonyangx  seems it modified to ```putIfAbsent```  here again in the later commit  ``` 5d7e502 :
fix license check error```

**Review by xwm1992 — APPROVED** [review]
